- NOTIFY_THIRSTIEOPS_REJECTED: 'thirstieops_rejected_order'
- NOTIFY_THIRSTIEOPS_SUBMITTED: 'thirstieops_submitted_order'
- NOTIFY_THIRSTIEOPS_ACCEPTED: 'thirstieops_accepted_order'
- NOTIFY_THIRSTIEOPS_RISKTRANSACTION: 'thirstieops_transaction_risk'
- NOTIFY_THIRSTIEOPS_LARGEORDER: 'thirstieops_large_order'
- STATUS_NOTIFY_THIRSTIEOPS:
  - SUBMITTED: NOTIFY_THIRSTIEOPS_SUBMITTED
  - REJECTED_MERCHANT: NOTIFY_THIRSTIEOPS_REJECTED
  - REJECTED_PAYMENT: NOTIFY_THIRSTIEOPS_REJECTED
  - REJECTED_PARTIAL: NOTIFY_THIRSTIEOPS_REJECTED
  - ACCEPTED: NOTIFY_THIRSTIEOPS_ACCEPTE
  - LARGE_ORDER: NOTIFY_THIRSTIEOPS_LARGEORDER
